---

name: Build & Release

on:
  push:
    tags:
      - '*'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


jobs:
  docker:
    name: Build and Release Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set versions tag
        run: |
          sed -i "s/version = \"[0-9]\+.[0-9]\+.[0-9]\+\"/version = \"${{github.ref_name}}\"/" pyproject.toml
          sed -i "s/__version__ = '[0-9]\+.[0-9]\+.[0-9]\+'/__version__ = '${{github.ref_name}}'/" app/__init__.py
          sed -i "s/version: [0-9]\+.[0-9]\+.[0-9]\+/version: ${{github.ref_name}}/" charts/mutating-webhook-no-cpu-limit/Chart.yaml
          sed -i "s/appVersion: [0-9]\+.[0-9]\+.[0-9]\+/appVersion: ${{github.ref_name}}/" charts/mutating-webhook-no-cpu-limit/Chart.yaml

      - name: Authenticate with Docker registry
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Install skaffold
        run: curl -Lo /tmp/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install /tmp/skaffold /usr/local/bin/

      - name: Run skaffold build
        run: skaffold build

  helm:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'source'

      - uses: actions/checkout@v3
        with:
          repository: 'deepworx/helm-charts'
          ssh-key: ${{ secrets.GA_SSH_KEY }}
          path: 'helm-charts'

      - name: Push local chart to helm-charts repo
        run: |
          rm -rf helm-charts/charts/mutating-webhook-no-cpu-limit
          cp -r source/charts/mutating-webhook-no-cpu-limit  helm-charts/charts/mutating-webhook-no-cpu-limit

          cd helm-charts
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add charts/mutating-webhook-no-cpu-limit
          git commit -m 'Sync helm chart files'
          git push
