---

name: Build & Release

on:
  push:
    tags:
      - '*'

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set versions tag
        run: |
          sed -i "s/version = \"[0-9]\+.[0-9]\+.[0-9]\+\"/version = \"${{github.ref_name}}\"/" pyproject.toml
          sed -i "s/__version__ = '[0-9]\+.[0-9]\+.[0-9]\+'/__version__ = '${{github.ref_name}}'/" app/__init__.py
          sed -i "s/version: [0-9]\+.[0-9]\+.[0-9]\+/version: ${{github.ref_name}}/" charts/mutating-webhook-no-cpu-limit/Chart.yaml
          sed -i "s/appVersion: [0-9]\+.[0-9]\+.[0-9]\+/appVersion: ${{github.ref_name}}/" charts/mutating-webhook-no-cpu-limit/Chart.yaml

      - name: Authenticate with Docker registry
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

      - name: Install skaffold
        run: curl -Lo /tmp/skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install /tmp/skaffold /usr/local/bin/

      - name: Run skaffold build
        run: skaffold build
