---

name: Build & Release

on:
  push:
    tags:
      - '*'

jobs:
  docker:
    name: Build and Release Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: deepworx/mutating-webhook-no-cpu-limit
          tags: |
            type=sha,format=short,prefix=,priority=100
            type=ref,event=branch
            type=ref,event=tag

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./compose/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  helm:
    name: Release Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: 'source'

      - uses: actions/checkout@v3
        with:
          repository: 'deepworx/helm-charts'
          ssh-key: ${{ secrets.GA_SSH_KEY }}
          path: 'helm-charts'

      - name: Push local chart to helm-charts repo
        run: |
          rm -rf helm-charts/charts/mutating-webhook-no-cpu-limit
          cp -r source/charts/mutating-webhook-no-cpu-limit  helm-charts/charts/mutating-webhook-no-cpu-limit

          cd helm-charts
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add charts/mutating-webhook-no-cpu-limit
          git commit -m 'Sync helm chart files'
          git push
